### ISSUE TITLE
journey.getReader fails if the connection of a mongo store is not successfully initialized

### ISSUE THREAD

**Issue by minhhien1996** [tungv/jerni#16]
Due to this null initialization: https://github.com/tungv/jerni/blob/4464d4715ff72952f44843f7337e3be499ab48fb/packages/store-mongo/lib/MongoDBStore.js#L44

sometime getReader fails at:
https://github.com/tungv/jerni/blob/4464d4715ff72952f44843f7337e3be499ab48fb/packages/store-mongo/lib/MongoDBStore.js#L147

**Comment by tungv** [comment]
Thanks for reporting. We probably need to wait for the connection to establish before returning underlaying collection. Will fix it in the next release.
